services:
  front:
    build: ./front
    ports:
      - "3000:3000"
    volumes:
      - ./front:/app
    environment:
      - NODE_ENV=development
    depends_on:
      - back

  back:
    build: ./back
    ports:
      - "8000:8000"
    volumes:
      - ./back:/app
    environment:
      - PYTHONUNBUFFERED=1
